apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: default  # Namespace where the Argo CD Application resource is created
spec:
  project: default
  source:
    repoURL: https://github.com/bhavana-186/ansib.git
    path: manifests
    targetRevision: HEAD
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: default  # Namespace where the application resources are deployed
  syncPolicy: {}
