- name: Installing apache
  yum:
   name: httpd
   state: present
- name: configuring apache
  copy:
   content: "Fred George"
   dest: /var/www/html/index.html
- name: Starting the service
  service:
   name: httpd
   state: started



