apiVersion: v1
kind: Secret
metadata:
  name: github-token-secret
  namespace: default
type: Opaque
data:
  token: Z2l0aHViX3BhdF8xMUEyVVFONFkweGt5SnRmSHhPTDRLX3RMQ1JlOU82NER2OEo0c0E3dmdoUW9temlBV1p0Q0c1dmNXTjRyVU9zS3JIWERDNVZMUDJKZk1zMlRr
