name: Deploy to Vault

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.0.0

    - name: Set Vault Address
      run: echo "VAULT_ADDR=${{ secrets.VAULT_ADDR }}" >> $GITHUB_ENV

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform
      env:
        VAULT_ADDR: ${{ secrets.VAULT_ADDR }}
        VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      run: |
        terraform apply -auto-approve \
          -var "vault_addr=${{ secrets.VAULT_ADDR }}" \
          -var "vault_token=${{ secrets.VAULT_TOKEN }}" \
          -var "db_username=${{ secrets.DB_USERNAME }}" \
          -var "db_password=${{ secrets.DB_PASSWORD }}"
